dist: dist
builds:
  - main: ./main.go
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
    ldflags:
      - -w -s
archives:
  - name_template: "{{ .ProjectName }}-{{ .Tag }}-{{ .Os }}-{{ .Arch }}"
    wrap_in_directory: false
    files:
      - LICENSE
checksum:
  name_template: 'CHECKSUM'
release:
  github:
    owner: grepplabs
    name: rabbitmq-mv
  draft: false
  prerelease: auto